sudo: false
os:
  - linux
  # - osx
language: python
python:
  - 2.7
install:  # install dependencies
  - pip install -r requirements.txt
  - pip install .
script:  # actual test
  - py.test --cov=pyprf_motion
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
